server {
    listen 443 ssl;
    http2 on;
    server_name bazarr.henrique.pw;

    location / {
        set $upstream http://bazarr:6767;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
