server {
    listen 443 ssl;
    http2 on;
    server_name home.henrique.pw;

    location / {
        set $upstream http://glance:8080;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
