server {
    listen 443 ssl;
    http2 on;
    server_name jackett.henrique.pw;

    location / {
        set $upstream http://jackett:9117;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
