server {
    listen 443 ssl;
    http2 on;
    server_name lidarr.henrique.pw;

    location / {
        set $upstream http://lidarr:8686;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
