server {
    listen 443 ssl;
    http2 on;
    server_name n8n.henrique.pw;

    location / {
        set $upstream http://n8n:5678;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
