server {
    listen 443 ssl;
    http2 on;
    server_name nzbget.henrique.pw;

    location / {
        set $upstream http://nzbget:6789;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
