server {
    listen 443 ssl;
    http2 on;
    server_name photo-tools.henrique.pw;

    location / {
        set $upstream http://power_tools:3000;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
