server {
    listen 443 ssl;
    http2 on;
    server_name photos.henrique.pw;

    location / {
        set $upstream http://immich-server:2283;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
