server {
    listen 443 ssl;
    http2 on;
    server_name prowlarr.henrique.pw;

    location / {
        set $upstream http://prowlarr:9696;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
