server {
    listen 443 ssl;
    http2 on;
    server_name sonarr.henrique.pw;

    location / {
        set $upstream http://sonarr:8989;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
