server {
    listen 443 ssl;
    http2 on;
    server_name suwayomi.henrique.pw;

    location / {
        set $upstream http://suwayomi:4567;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
