server {
    listen 443 ssl;
    http2 on;
    server_name tv.henrique.pw;

    location / {
        set $upstream http://jellyfin:8096;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
