server {
    listen 443 ssl;
    http2 on;
    server_name tvv.henrique.pw;

    location / {
        set $upstream http://seerr:5055;
        proxy_pass $upstream$request_uri;
        include /etc/nginx/snippets/proxy.conf;
    }
}
