name: reader

services:
  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:stable
    container_name: suwayomi
    restart: unless-stopped
    volumes: # The order matters! Make sure the downloads is first in the volume list or it will not work!
      - ${MEDIA_DIR}/mangas:/home/suwayomi/.local/share/Tachidesk/downloads
      - ${MEDIA_DIR}/tachidesk:/home/suwayomi/.local/share/Tachidesk
    ports:
      - "9910:4567"
    labels:
      glance.hide: false
      glance.id: suwayomi
      glance.name: Suwayomi
      glance.icon: si:suwayomi
      glance.url: http://mini:9910
      glance.description: Manga Downloader

  komf:
    image: sndxr/komf:latest
    container_name: komf
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - KOMF_KOMGA_BASE_URI=http://komga:9913
      - KOMF_KOMGA_USER=henriquepw4@gmail.com
      - KOMF_KOMGA_PASSWORD=123123
      - KOMF_LOG_LEVEL=INFO
      - JAVA_TOOL_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:ShenandoahGuaranteedGCInterval=3600000 -XX:TrimNativeHeapInterval=3600000
    volumes:
      - ./komf/config:/config #path to directory with application.yml and database file
    ports:
      - "9911:8085"
    labels:
      glance.hide: false
      glance.parent: komga
      glance.name: Metadata

  # kavita:
  #   image: jvmilazz0/kavita
  #   container_name: kavita
  #   restart: unless-stopped
  #   volumes:
  #     - ${MEDIA_DIR}/mangas:/mangas
  #     - ${MEDIA_DIR}/comics:/comics
  #     - ${MEDIA_DIR}/books:/books
  #     - ./kavita/config:/kavita/config
  #   ports:
  #     - "9912:5000"

  komga:
    image: gotson/komga
    container_name: komga
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - ../../.env
    volumes:
      - type: bind
        source: ./komga/config
        target: /config
      - type: bind
        source: ${MEDIA_DIR}
        target: /data
    ports:
      - "9913:25600"
    labels:
      glance.hide: false
      glance.id: komga
      glance.name: Komga
      glance.icon: si:komga
      glance.url: http://mini:9913
      glance.description: Manga & Comics
