name: nextcloud
services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    init: true
    restart: always
    ports:
      - "9980:8080"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tty: true
    labels:
      glance.hide: false
      glance.name: Nextcloud

volumes:
  nextcloud_aio_mastercontainer:
    external: true
