name: glance

networks:
  dnet:
    external: true

services:
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    networks:
      - dnet
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ../../.env
