services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: memorium
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APPS_DIR}/syncthing:/var/syncthing
    network_mode: host
    restart: unless-stopped
    labels:
      glance.hide: false
      glance.id: syncthing
      glance.name: Syncthing
      glance.icon: si:syncthing
      glance.description: Backup & Sync
