name: jellyfin
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8097:8096/tcp
      - 7360:7359/udp
    volumes:
      - ${APPS_DIR}/jellyfin/config:/config
      - ${APPS_DIR}/jellyfin/cache:/cache
      - type: bind
        source: ${MEDIA_DIR}/videos
        target: /media/videos
      - type: bind
        source: ${MEDIA_DIR}/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: "unless-stopped"
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      glance.hide: false
      glance.id: jellyfin
      glance.name: Jellyfin
      glance.icon: si:jellyfin
      glance.url: https://tv.henrique.pw
      glance.description: Movies & shows
